# Generated by Django 3.1.7 on 2021-05-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='discounts',
            new_name='discount',
        ),
    ]
